package com.bitcom.portal.employee;

public enum AuditAction {
    EMPLOYEE_CREATED, EMPLOYEE_UPDATED, BGCHECK_REQUESTED, BGCHECK_VIEWED, BGCHECK_DELETED,
    EMPLOYEE_RESIGNED, PASSWORD_RESET, ACCOUNT_LOCKED
}
